version: '3.3'

volumes:
  media:
  static:
  database_data:

services:
  foodgram-database:
    container_name: foodgram-database
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  foodgram-backend:
    container_name: foodgram-backend
    build: ../backend/foodgram-st
    volumes:
      - media:/app/media_files/
      - static:/backend_static_files/
    depends_on:
      - foodgram-database
    env_file: .env
    ports:
      - 8000:8000

  foodgram-gateway:
    image: nginx:1.19.3
    container_name: foodgram-gateway
    volumes:
      - static:/backend_static_files/
      - media:/app/media_files/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80
    depends_on:
      - foodgram-backend
    env_file: .env

  foogram-frontend:
    container_name: foogram-frontend
    build: ../frontend/
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - foodgram-backend
      - foodgram-database
    env_file: .env
  
