name: Main foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
  
        env:
          POSTGRES_PASSWORD: postgres_test_password
          POSTGRES_DB: postgres_test_db
          POSTGRES_USER: postgres_test_user
        ports:
          - 5432:5432
        
        options: --health-cmd pg_isready --health-interval 15s --health-retries 5 --health-timeout 10s
    steps:
    - name: Check out foodgram code
      uses: actions/checkout@v4
    - name: Set up Python-3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r ./backend/foodgram-st/requirements.txt
        pip install ruff==0.8.0
    
    - name: Lint with ruff and run django tests
      
      env:
        POSTGRES_PASSWORD: postgres_test_password
        POSTGRES_DB: postgres_test_db
        POSTGRES_USER: postgres_test_user
        
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        python -m ruff check backend/
        cd backend/
        python manage.py test